# Generated by Django 3.2 on 2022-03-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_sys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='invite_code',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
