# Generated by Django 3.2 on 2022-04-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_sys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='invited_by',
        ),
        migrations.DeleteModel(
            name='SMSCodes',
        ),
        migrations.AlterField(
            model_name='integratedprofile',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='integratedprofile',
            name='password',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
