# Generated by Django 3.2 on 2022-04-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral_sys', '0002_auto_20220412_0027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integratedprofile',
            options={'ordering': ['phone_number']},
        ),
    ]
