# Generated by Django 3.2 on 2022-04-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_sys', '0002_auto_20220326_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCodes',
            fields=[
                ('expected_code', models.CharField(max_length=4)),
                ('phone_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
        ),
    ]
