# Generated by Django 3.2 on 2022-04-14 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referral_sys', '0003_alter_integratedprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integratedprofile',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='invite_code'),
        ),
    ]
